networks:
  qryn-e2e:
    driver: bridge
services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.8
    hostname: clickhouse
    networks:
      - qryn-e2e
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:8123/?query=SELECT%201 || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5

  qryn:
    image: "oven/bun:1.1.27"
    hostname: qryn
    networks:
      - qryn-e2e
    volumes:
      - ../../../../:/qryn
    depends_on:
      - clickhouse
    working_dir: /qryn
    environment:
      CLICKHOUSE_SERVER: clickhouse
      CLICKHOUSE_DB: qryn
      QRYN_LOGIN: a
      QRYN_PASSWORD: b
      DEBUG: "1"
    ports:
      - 3100:3100
    command:
      - sh
      - -c
      - "sleep 5 && bun install && bun --bun qryn.mjs"
    healthcheck:
      test: "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1"
      interval: 5s
      timeout: 5s
      retries: 5

  otel-collector:
    image: ghcr.io/metrico/qryn-otel-collector:0.0.11
    hostname: otel-collector
    ports:
      - 8062:8062
    depends_on:
      - clickhouse
      - qryn
    networks:
      - qryn-e2e
    volumes:
      - ./otel-collector.yaml:/etc/otel/config.yaml
